ALTER TABLE user_preferences
  ADD COLUMN IF NOT EXISTS auto_sync BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS sync_frequency VARCHAR(20) NOT NULL DEFAULT 'Every 6 hours',
  ADD COLUMN IF NOT EXISTS workspace_name VARCHAR(100) NOT NULL DEFAULT 'My Shopify Apps',
  ADD COLUMN IF NOT EXISTS currency VARCHAR(3) NOT NULL DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS timezone VARCHAR(50) NOT NULL DEFAULT 'America/New_York';
