// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS0eqroCDyj7E87tUCVnUgwhXTNV9zv-g',
    appId: '1:761541341095:web:ae2607c9547a090011d082',
    messagingSenderId: '761541341095',
    projectId: 'ledgerguard-c7557',
    authDomain: 'ledgerguard-c7557.firebaseapp.com',
    storageBucket: 'ledgerguard-c7557.firebasestorage.app',
    measurementId: 'G-XJ1QZTCG2P',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYRaLqbF_RUsOX-dnE4inE9iMJsiGckPs',
    appId: '1:761541341095:ios:eb8ab14fe3a1780811d082',
    messagingSenderId: '761541341095',
    projectId: 'ledgerguard-c7557',
    storageBucket: 'ledgerguard-c7557.firebasestorage.app',
    iosBundleId: 'com.example.ledgerguard',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7IoHNWWc6VlpgL_oX40uGsCYOzAexW-4',
    appId: '1:761541341095:android:e4a78198a3a361a511d082',
    messagingSenderId: '761541341095',
    projectId: 'ledgerguard-c7557',
    storageBucket: 'ledgerguard-c7557.firebasestorage.app',
  );
}
