// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type App struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	PartnerAppID    string `json:"partnerAppId"`
	TrackingEnabled bool   `json:"trackingEnabled"`
	InstallCount    int    `json:"installCount"`
}

type AppSubscription struct {
	ID                 string                  `json:"id"`
	Domain             string                  `json:"domain"`
	ShopName           string                  `json:"shopName"`
	Plan               *string                 `json:"plan,omitempty"`
	Status             AppSubscriptionStatus   `json:"status"`
	RiskState          RiskState               `json:"riskState"`
	MrrCents           int                     `json:"mrrCents"`
	Currency           string                  `json:"currency"`
	DaysPastDue        *int                    `json:"daysPastDue,omitempty"`
	LastPaymentDate    *time.Time              `json:"lastPaymentDate,omitempty"`
	ExpectedNextCharge *time.Time              `json:"expectedNextCharge,omitempty"`
	BillingInterval    BillingInterval         `json:"billingInterval"`
	Events             []*AppSubscriptionEvent `json:"events"`
}

type AppSubscriptionConnection struct {
	Nodes      []*AppSubscription `json:"nodes"`
	TotalCount int                `json:"totalCount"`
	PageInfo   *PageInfo          `json:"pageInfo"`
}

type AppSubscriptionEvent struct {
	ID            string    `json:"id"`
	EventType     string    `json:"eventType"`
	FromStatus    *string   `json:"fromStatus,omitempty"`
	ToStatus      *string   `json:"toStatus,omitempty"`
	FromRiskState *string   `json:"fromRiskState,omitempty"`
	ToRiskState   *string   `json:"toRiskState,omitempty"`
	Reason        *string   `json:"reason,omitempty"`
	OccurredAt    time.Time `json:"occurredAt"`
}

type DailySnapshot struct {
	Date               time.Time `json:"date"`
	ActiveMrrCents     int       `json:"activeMrrCents"`
	RenewalSuccessRate float64   `json:"renewalSuccessRate"`
	RevenueAtRiskCents int       `json:"revenueAtRiskCents"`
	SafeCount          int       `json:"safeCount"`
	ChurnedCount       int       `json:"churnedCount"`
}

type Earnings struct {
	RecurringCents int `json:"recurringCents"`
	UsageCents     int `json:"usageCents"`
	OneTimeCents   int `json:"oneTimeCents"`
	RefundCents    int `json:"refundCents"`
	TotalCents     int `json:"totalCents"`
}

type Metrics struct {
	ActiveMrrCents       int     `json:"activeMrrCents"`
	RevenueAtRiskCents   int     `json:"revenueAtRiskCents"`
	UsageRevenueCents    int     `json:"usageRevenueCents"`
	TotalRevenueCents    int     `json:"totalRevenueCents"`
	RenewalSuccessRate   float64 `json:"renewalSuccessRate"`
	SafeCount            int     `json:"safeCount"`
	OneCycleMissedCount  int     `json:"oneCycleMissedCount"`
	TwoCyclesMissedCount int     `json:"twoCyclesMissedCount"`
	ChurnedCount         int     `json:"churnedCount"`
}

type PageInfo struct {
	HasNextPage     bool `json:"hasNextPage"`
	HasPreviousPage bool `json:"hasPreviousPage"`
}

type Query struct {
}

type RiskSummary struct {
	TotalSubscriptions  int                `json:"totalSubscriptions"`
	Safe                int                `json:"safe"`
	OneCycleMissed      int                `json:"oneCycleMissed"`
	TwoCyclesMissed     int                `json:"twoCyclesMissed"`
	Churned             int                `json:"churned"`
	RevenueAtRiskCents  int                `json:"revenueAtRiskCents"`
	AtRiskSubscriptions []*AppSubscription `json:"atRiskSubscriptions"`
}

type StoreHealth struct {
	Domain          string           `json:"domain"`
	ShopName        string           `json:"shopName"`
	IsPaid          bool             `json:"isPaid"`
	RiskState       RiskState        `json:"riskState"`
	Subscription    *AppSubscription `json:"subscription,omitempty"`
	LastPaymentDate *time.Time       `json:"lastPaymentDate,omitempty"`
	DaysPastDue     *int             `json:"daysPastDue,omitempty"`
}

type Transaction struct {
	ID               string           `json:"id"`
	Domain           string           `json:"domain"`
	ShopName         string           `json:"shopName"`
	ChargeType       ChargeType       `json:"chargeType"`
	GrossAmountCents int              `json:"grossAmountCents"`
	NetAmountCents   int              `json:"netAmountCents"`
	Currency         string           `json:"currency"`
	TransactionDate  time.Time        `json:"transactionDate"`
	SubscriptionGid  *string          `json:"subscriptionGid,omitempty"`
	BillingInterval  *BillingInterval `json:"billingInterval,omitempty"`
}

type TransactionConnection struct {
	Nodes      []*Transaction `json:"nodes"`
	TotalCount int            `json:"totalCount"`
	PageInfo   *PageInfo      `json:"pageInfo"`
}

type AppSubscriptionStatus string

const (
	AppSubscriptionStatusActive      AppSubscriptionStatus = "ACTIVE"
	AppSubscriptionStatusCancelled   AppSubscriptionStatus = "CANCELLED"
	AppSubscriptionStatusFrozen      AppSubscriptionStatus = "FROZEN"
	AppSubscriptionStatusPending     AppSubscriptionStatus = "PENDING"
	AppSubscriptionStatusUninstalled AppSubscriptionStatus = "UNINSTALLED"
)

var AllAppSubscriptionStatus = []AppSubscriptionStatus{
	AppSubscriptionStatusActive,
	AppSubscriptionStatusCancelled,
	AppSubscriptionStatusFrozen,
	AppSubscriptionStatusPending,
	AppSubscriptionStatusUninstalled,
}

func (e AppSubscriptionStatus) IsValid() bool {
	switch e {
	case AppSubscriptionStatusActive, AppSubscriptionStatusCancelled, AppSubscriptionStatusFrozen, AppSubscriptionStatusPending, AppSubscriptionStatusUninstalled:
		return true
	}
	return false
}

func (e AppSubscriptionStatus) String() string {
	return string(e)
}

func (e *AppSubscriptionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AppSubscriptionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AppSubscriptionStatus", str)
	}
	return nil
}

func (e AppSubscriptionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AppSubscriptionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AppSubscriptionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BillingInterval string

const (
	BillingIntervalMonthly BillingInterval = "MONTHLY"
	BillingIntervalAnnual  BillingInterval = "ANNUAL"
)

var AllBillingInterval = []BillingInterval{
	BillingIntervalMonthly,
	BillingIntervalAnnual,
}

func (e BillingInterval) IsValid() bool {
	switch e {
	case BillingIntervalMonthly, BillingIntervalAnnual:
		return true
	}
	return false
}

func (e BillingInterval) String() string {
	return string(e)
}

func (e *BillingInterval) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BillingInterval(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BillingInterval", str)
	}
	return nil
}

func (e BillingInterval) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BillingInterval) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BillingInterval) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ChargeType string

const (
	ChargeTypeRecurring ChargeType = "RECURRING"
	ChargeTypeUsage     ChargeType = "USAGE"
	ChargeTypeOneTime   ChargeType = "ONE_TIME"
	ChargeTypeRefund    ChargeType = "REFUND"
)

var AllChargeType = []ChargeType{
	ChargeTypeRecurring,
	ChargeTypeUsage,
	ChargeTypeOneTime,
	ChargeTypeRefund,
}

func (e ChargeType) IsValid() bool {
	switch e {
	case ChargeTypeRecurring, ChargeTypeUsage, ChargeTypeOneTime, ChargeTypeRefund:
		return true
	}
	return false
}

func (e ChargeType) String() string {
	return string(e)
}

func (e *ChargeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChargeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChargeType", str)
	}
	return nil
}

func (e ChargeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChargeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChargeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RiskState string

const (
	RiskStateSafe            RiskState = "SAFE"
	RiskStateOneCycleMissed  RiskState = "ONE_CYCLE_MISSED"
	RiskStateTwoCyclesMissed RiskState = "TWO_CYCLES_MISSED"
	RiskStateChurned         RiskState = "CHURNED"
)

var AllRiskState = []RiskState{
	RiskStateSafe,
	RiskStateOneCycleMissed,
	RiskStateTwoCyclesMissed,
	RiskStateChurned,
}

func (e RiskState) IsValid() bool {
	switch e {
	case RiskStateSafe, RiskStateOneCycleMissed, RiskStateTwoCyclesMissed, RiskStateChurned:
		return true
	}
	return false
}

func (e RiskState) String() string {
	return string(e)
}

func (e *RiskState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RiskState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RiskState", str)
	}
	return nil
}

func (e RiskState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RiskState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RiskState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
