package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to
// the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sachin-sivadasan/ledgerguard/internal/domain/entity"
	"github.com/sachin-sivadasan/ledgerguard/internal/domain/repository"
	"github.com/sachin-sivadasan/ledgerguard/internal/domain/valueobject"
	"github.com/sachin-sivadasan/ledgerguard/internal/interfaces/http/middleware"
)

// Subscriptions is the resolver for the subscriptions field.
func (r *queryResolver) Subscriptions(ctx context.Context, appID string, riskState *RiskState, status *AppSubscriptionStatus, domain *string, limit *int, offset *int) (*AppSubscriptionConnection, error) {
	appUUID, err := uuid.Parse(appID)
	if err != nil {
		return nil, fmt.Errorf("invalid app ID: %w", err)
	}

	filters := repository.SubscriptionFilters{
		Page:      1,
		PageSize:  derefInt(limit, 50),
		SortBy:    "base_price_cents",
		SortOrder: "desc",
	}

	if riskState != nil {
		filters.RiskStates = []valueobject.RiskState{valueobject.RiskState(riskState.String())}
	}

	if domain != nil {
		filters.SearchTerm = *domain
	}

	if offset != nil && *offset > 0 {
		filters.Page = (*offset / filters.PageSize) + 1
	}

	page, err := r.SubscriptionRepo.FindWithFilters(ctx, appUUID, filters)
	if err != nil {
		return nil, fmt.Errorf("failed to query subscriptions: %w", err)
	}

	now := time.Now()
	nodes := make([]*AppSubscription, 0, len(page.Subscriptions))
	for _, sub := range page.Subscriptions {
		nodes = append(nodes, mapEntitySubscription(sub, now))
	}

	offsetVal := derefInt(offset, 0)
	limitVal := derefInt(limit, 50)

	return &AppSubscriptionConnection{
		Nodes:      nodes,
		TotalCount: page.Total,
		PageInfo: &PageInfo{
			HasNextPage:     offsetVal+limitVal < page.Total,
			HasPreviousPage: offsetVal > 0,
		},
	}, nil
}

// Subscription is the resolver for the subscription field.
func (r *queryResolver) Subscription(ctx context.Context, id string) (*AppSubscription, error) {
	subUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid subscription ID: %w", err)
	}

	sub, err := r.SubscriptionRepo.FindByID(ctx, subUUID)
	if err != nil {
		return nil, fmt.Errorf("subscription not found: %w", err)
	}

	return mapEntitySubscription(sub, time.Now()), nil
}

// Metrics is the resolver for the metrics field.
func (r *queryResolver) Metrics(ctx context.Context, appID string) (*Metrics, error) {
	appUUID, err := uuid.Parse(appID)
	if err != nil {
		return nil, fmt.Errorf("invalid app ID: %w", err)
	}

	snapshot, err := r.SnapshotRepo.FindLatestByAppID(ctx, appUUID)
	if err != nil {
		return nil, fmt.Errorf("no metrics found: %w", err)
	}

	return &Metrics{
		ActiveMrrCents:       int(snapshot.ActiveMRRCents),
		RevenueAtRiskCents:   int(snapshot.RevenueAtRiskCents),
		UsageRevenueCents:    int(snapshot.UsageRevenueCents),
		TotalRevenueCents:    int(snapshot.TotalRevenueCents),
		RenewalSuccessRate:   snapshot.RenewalSuccessRate,
		SafeCount:            snapshot.SafeCount,
		OneCycleMissedCount:  snapshot.OneCycleMissedCount,
		TwoCyclesMissedCount: snapshot.TwoCyclesMissedCount,
		ChurnedCount:         snapshot.ChurnedCount,
	}, nil
}

// MetricsTrend is the resolver for the metricsTrend field.
func (r *queryResolver) MetricsTrend(ctx context.Context, appID string, months *int) ([]*DailySnapshot, error) {
	appUUID, err := uuid.Parse(appID)
	if err != nil {
		return nil, fmt.Errorf("invalid app ID: %w", err)
	}

	m := derefInt(months, 6)
	to := time.Now()
	from := to.AddDate(0, -m, 0)

	snapshots, err := r.SnapshotRepo.FindByAppIDRange(ctx, appUUID, from, to)
	if err != nil {
		return nil, fmt.Errorf("failed to query metrics trend: %w", err)
	}

	result := make([]*DailySnapshot, 0, len(snapshots))
	for _, s := range snapshots {
		result = append(result, &DailySnapshot{
			Date:               s.Date,
			ActiveMrrCents:     int(s.ActiveMRRCents),
			RenewalSuccessRate: s.RenewalSuccessRate,
			RevenueAtRiskCents: int(s.RevenueAtRiskCents),
			SafeCount:          s.SafeCount,
			ChurnedCount:       s.ChurnedCount,
		})
	}
	return result, nil
}

// StoreHealth is the resolver for the storeHealth field.
func (r *queryResolver) StoreHealth(ctx context.Context, appID string, domain string) (*StoreHealth, error) {
	appUUID, err := uuid.Parse(appID)
	if err != nil {
		return nil, fmt.Errorf("invalid app ID: %w", err)
	}

	sub, err := r.SubscriptionRepo.FindByAppIDAndDomain(ctx, appUUID, domain)
	if err != nil {
		return &StoreHealth{
			Domain:    domain,
			ShopName:  domain,
			IsPaid:    false,
			RiskState: RiskStateChurned,
		}, nil
	}

	now := time.Now()
	daysPastDue := r.RiskEngine.DaysPastDue(sub, now)
	isPaid := sub.RiskState == valueobject.RiskStateSafe

	mapped := mapEntitySubscription(sub, now)
	health := &StoreHealth{
		Domain:       domain,
		ShopName:     sub.ShopName,
		IsPaid:       isPaid,
		RiskState:    RiskState(sub.RiskState),
		Subscription: mapped,
	}

	if sub.LastRecurringChargeDate != nil {
		health.LastPaymentDate = sub.LastRecurringChargeDate
	}
	if daysPastDue > 0 {
		health.DaysPastDue = &daysPastDue
	}

	return health, nil
}

// Earnings is the resolver for the earnings field.
func (r *queryResolver) Earnings(ctx context.Context, appID string) (*Earnings, error) {
	appUUID, err := uuid.Parse(appID)
	if err != nil {
		return nil, fmt.Errorf("invalid app ID: %w", err)
	}

	now := time.Now()
	from := now.AddDate(-1, 0, 0)
	txs, err := r.TransactionRepo.FindByAppID(ctx, appUUID, from, now)
	if err != nil {
		return nil, fmt.Errorf("failed to query transactions: %w", err)
	}

	var recurringCents, usageCents, oneTimeCents, refundCents int64
	for _, tx := range txs {
		switch tx.ChargeType {
		case valueobject.ChargeTypeRecurring:
			recurringCents += tx.AmountCents()
		case valueobject.ChargeTypeUsage:
			usageCents += tx.AmountCents()
		case valueobject.ChargeTypeOneTime:
			oneTimeCents += tx.AmountCents()
		case valueobject.ChargeTypeRefund:
			refundCents += tx.AmountCents()
		}
	}

	total := recurringCents + usageCents + oneTimeCents - refundCents

	return &Earnings{
		RecurringCents: int(recurringCents),
		UsageCents:     int(usageCents),
		OneTimeCents:   int(oneTimeCents),
		RefundCents:    int(refundCents),
		TotalCents:     int(total),
	}, nil
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, appID string, chargeType *ChargeType, domain *string, startDate *time.Time, endDate *time.Time, limit *int, offset *int) (*TransactionConnection, error) {
	appUUID, err := uuid.Parse(appID)
	if err != nil {
		return nil, fmt.Errorf("invalid app ID: %w", err)
	}

	now := time.Now()
	from := now.AddDate(-1, 0, 0)
	to := now
	if startDate != nil {
		from = *startDate
	}
	if endDate != nil {
		to = *endDate
	}

	var txs []*entity.Transaction
	if domain != nil {
		txs, err = r.TransactionRepo.FindByDomain(ctx, appUUID, *domain, from, to)
	} else {
		txs, err = r.TransactionRepo.FindByAppID(ctx, appUUID, from, to)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to query transactions: %w", err)
	}

	// Filter by charge type if specified
	if chargeType != nil {
		ct := valueobject.ChargeType(chargeType.String())
		filtered := make([]*entity.Transaction, 0)
		for _, tx := range txs {
			if tx.ChargeType == ct {
				filtered = append(filtered, tx)
			}
		}
		txs = filtered
	}

	totalCount := len(txs)

	// Apply pagination
	offsetVal := derefInt(offset, 0)
	limitVal := derefInt(limit, 50)
	if offsetVal > len(txs) {
		txs = nil
	} else {
		end := offsetVal + limitVal
		if end > len(txs) {
			end = len(txs)
		}
		txs = txs[offsetVal:end]
	}

	nodes := make([]*Transaction, 0, len(txs))
	for _, tx := range txs {
		nodes = append(nodes, mapEntityTransaction(tx))
	}

	return &TransactionConnection{
		Nodes:      nodes,
		TotalCount: totalCount,
		PageInfo: &PageInfo{
			HasNextPage:     offsetVal+limitVal < totalCount,
			HasPreviousPage: offsetVal > 0,
		},
	}, nil
}

// RiskSummary is the resolver for the riskSummary field.
func (r *queryResolver) RiskSummary(ctx context.Context, appID string) (*RiskSummary, error) {
	appUUID, err := uuid.Parse(appID)
	if err != nil {
		return nil, fmt.Errorf("invalid app ID: %w", err)
	}

	subs, err := r.SubscriptionRepo.FindByAppID(ctx, appUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to query subscriptions: %w", err)
	}

	now := time.Now()
	summary := r.RiskEngine.CalculateRiskSummary(subs)

	atRisk := make([]*AppSubscription, 0)
	for _, sub := range subs {
		if sub.RiskState.IsAtRisk() {
			atRisk = append(atRisk, mapEntitySubscription(sub, now))
		}
	}

	revenueAtRisk := r.RiskEngine.CalculateRevenueAtRisk(subs)
	total := summary.SafeCount + summary.OneCycleMissedCount + summary.TwoCyclesMissedCount + summary.ChurnedCount

	return &RiskSummary{
		TotalSubscriptions:  total,
		Safe:                summary.SafeCount,
		OneCycleMissed:      summary.OneCycleMissedCount,
		TwoCyclesMissed:     summary.TwoCyclesMissedCount,
		Churned:             summary.ChurnedCount,
		RevenueAtRiskCents:  int(revenueAtRisk),
		AtRiskSubscriptions: atRisk,
	}, nil
}

// Apps is the resolver for the apps field.
func (r *queryResolver) Apps(ctx context.Context) ([]*App, error) {
	user := middleware.UserFromContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("authentication required")
	}

	partnerAccount, err := r.PartnerAccountRepo.FindByUserID(ctx, user.ID)
	if err != nil {
		return nil, fmt.Errorf("no partner account found: %w", err)
	}

	apps, err := r.AppRepo.FindByPartnerAccountID(ctx, partnerAccount.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to query apps: %w", err)
	}

	result := make([]*App, 0, len(apps))
	for _, a := range apps {
		result = append(result, &App{
			ID:              a.ID.String(),
			Name:            a.Name,
			PartnerAppID:    a.PartnerAppID,
			TrackingEnabled: a.TrackingEnabled,
			InstallCount:    a.InstallCount,
		})
	}
	return result, nil
}

// App is the resolver for the app field.
func (r *queryResolver) App(ctx context.Context, id string) (*App, error) {
	appUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid app ID: %w", err)
	}

	a, err := r.AppRepo.FindByID(ctx, appUUID)
	if err != nil {
		return nil, fmt.Errorf("app not found: %w", err)
	}

	return &App{
		ID:              a.ID.String(),
		Name:            a.Name,
		PartnerAppID:    a.PartnerAppID,
		TrackingEnabled: a.TrackingEnabled,
		InstallCount:    a.InstallCount,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// --- Helper functions ---

func mapEntitySubscription(sub *entity.Subscription, now time.Time) *AppSubscription {
	s := &AppSubscription{
		ID:              sub.ID.String(),
		Domain:          sub.MyshopifyDomain,
		ShopName:        sub.ShopName,
		Status:          AppSubscriptionStatus(sub.Status),
		RiskState:       RiskState(sub.RiskState),
		MrrCents:        int(sub.MRRCents()),
		Currency:        sub.Currency,
		BillingInterval: BillingInterval(sub.BillingInterval),
	}

	if sub.PlanName != "" {
		plan := sub.PlanName
		s.Plan = &plan
	}

	if sub.LastRecurringChargeDate != nil {
		s.LastPaymentDate = sub.LastRecurringChargeDate
	}

	if sub.ExpectedNextChargeDate != nil {
		s.ExpectedNextCharge = sub.ExpectedNextChargeDate
	}

	if sub.ExpectedNextChargeDate != nil && now.After(*sub.ExpectedNextChargeDate) {
		days := int(now.Sub(*sub.ExpectedNextChargeDate).Hours() / 24)
		s.DaysPastDue = &days
	}

	return s
}

func mapEntityTransaction(tx *entity.Transaction) *Transaction {
	t := &Transaction{
		ID:               tx.ID.String(),
		Domain:           tx.MyshopifyDomain,
		ShopName:         tx.ShopName,
		ChargeType:       ChargeType(tx.ChargeType),
		GrossAmountCents: int(tx.GrossAmountCents),
		NetAmountCents:   int(tx.AmountCents()),
		Currency:         tx.Currency,
		TransactionDate:  tx.CreatedDate,
	}
	if tx.SubscriptionGID != "" {
		t.SubscriptionGid = &tx.SubscriptionGID
	}
	if tx.BillingInterval != "" {
		bi := BillingInterval(tx.BillingInterval)
		t.BillingInterval = &bi
	}
	return t
}

func derefInt(p *int, def int) int {
	if p != nil {
		return *p
	}
	return def
}
