import '../models/event_model.dart';

final _now = DateTime.now();

final mockEvents = <AppEvent>[
  // --- Installs (12) ---
  AppEvent(
    id: 'evt-1', date: _now.subtract(const Duration(days: 0, hours: 3)),
    type: EventType.appInstall, appId: 'app-1',
    storeDomain: 'bright-gadgets.myshopify.com',
    title: 'InventorySync Pro installed',
    description: 'bright-gadgets installed InventorySync Pro',
  ),
  AppEvent(
    id: 'evt-2', date: _now.subtract(const Duration(days: 1, hours: 5)),
    type: EventType.appInstall, appId: 'app-2',
    storeDomain: 'eco-shop.myshopify.com',
    title: 'ReviewBoost installed',
    description: 'eco-shop installed ReviewBoost',
  ),
  AppEvent(
    id: 'evt-3', date: _now.subtract(const Duration(days: 2)),
    type: EventType.appInstall, appId: 'app-3',
    storeDomain: 'daily-deals.myshopify.com',
    title: 'ShipTracker installed',
    description: 'daily-deals installed ShipTracker',
  ),
  AppEvent(
    id: 'evt-4', date: _now.subtract(const Duration(days: 3)),
    type: EventType.appInstall, appId: 'app-1',
    storeDomain: 'fresh-foods.myshopify.com',
    title: 'InventorySync Pro installed',
    description: 'fresh-foods installed InventorySync Pro',
  ),
  AppEvent(
    id: 'evt-5', date: _now.subtract(const Duration(days: 5)),
    type: EventType.appInstall, appId: 'app-2',
    storeDomain: 'glow-beauty.myshopify.com',
    title: 'ReviewBoost installed',
    description: 'glow-beauty installed ReviewBoost',
  ),
  AppEvent(
    id: 'evt-6', date: _now.subtract(const Duration(days: 7)),
    type: EventType.appInstall, appId: 'app-1',
    storeDomain: 'cool-threads.myshopify.com',
    title: 'InventorySync Pro installed',
    description: 'cool-threads installed InventorySync Pro',
  ),
  AppEvent(
    id: 'evt-7', date: _now.subtract(const Duration(days: 9)),
    type: EventType.appInstall, appId: 'app-3',
    storeDomain: 'acme-store.myshopify.com',
    title: 'ShipTracker installed',
    description: 'acme-store installed ShipTracker',
  ),
  AppEvent(
    id: 'evt-8', date: _now.subtract(const Duration(days: 12)),
    type: EventType.appInstall, appId: 'app-2',
    storeDomain: 'alpha-outlet.myshopify.com',
    title: 'ReviewBoost installed',
    description: 'alpha-outlet installed ReviewBoost',
  ),
  AppEvent(
    id: 'evt-9', date: _now.subtract(const Duration(days: 15)),
    type: EventType.appInstall, appId: 'app-1',
    storeDomain: 'beta-mart.myshopify.com',
    title: 'InventorySync Pro installed',
    description: 'beta-mart installed InventorySync Pro',
  ),
  AppEvent(
    id: 'evt-10', date: _now.subtract(const Duration(days: 18)),
    type: EventType.appInstall, appId: 'app-3',
    storeDomain: 'craft-corner.myshopify.com',
    title: 'ShipTracker installed',
    description: 'craft-corner installed ShipTracker',
  ),
  AppEvent(
    id: 'evt-11', date: _now.subtract(const Duration(days: 22)),
    type: EventType.appInstall, appId: 'app-1',
    storeDomain: 'dusk-decor.myshopify.com',
    title: 'InventorySync Pro installed',
    description: 'dusk-decor installed InventorySync Pro',
  ),
  AppEvent(
    id: 'evt-12', date: _now.subtract(const Duration(days: 27)),
    type: EventType.appInstall, appId: 'app-2',
    storeDomain: 'ink-press.myshopify.com',
    title: 'ReviewBoost installed',
    description: 'ink-press installed ReviewBoost',
  ),

  // --- Billing Success (10) ---
  AppEvent(
    id: 'evt-13', date: _now.subtract(const Duration(hours: 6)),
    type: EventType.billingSuccess, appId: 'app-1',
    storeDomain: 'acme-store.myshopify.com',
    title: 'Billing succeeded',
    description: 'Recurring charge \$49.99 collected from acme-store',
    metadata: {'amount': '4999'},
  ),
  AppEvent(
    id: 'evt-14', date: _now.subtract(const Duration(days: 1, hours: 2)),
    type: EventType.billingSuccess, appId: 'app-2',
    storeDomain: 'eco-shop.myshopify.com',
    title: 'Billing succeeded',
    description: 'Recurring charge \$19.99 collected from eco-shop',
    metadata: {'amount': '1999'},
  ),
  AppEvent(
    id: 'evt-15', date: _now.subtract(const Duration(days: 2, hours: 8)),
    type: EventType.billingSuccess, appId: 'app-1',
    storeDomain: 'bright-gadgets.myshopify.com',
    title: 'Billing succeeded',
    description: 'Recurring charge \$49.99 collected from bright-gadgets',
    metadata: {'amount': '4999'},
  ),
  AppEvent(
    id: 'evt-16', date: _now.subtract(const Duration(days: 4)),
    type: EventType.billingSuccess, appId: 'app-3',
    storeDomain: 'fresh-foods.myshopify.com',
    title: 'Billing succeeded',
    description: 'Recurring charge \$49.99 collected from fresh-foods',
    metadata: {'amount': '4999'},
  ),
  AppEvent(
    id: 'evt-17', date: _now.subtract(const Duration(days: 6)),
    type: EventType.billingSuccess, appId: 'app-2',
    storeDomain: 'cool-threads.myshopify.com',
    title: 'Billing succeeded',
    description: 'Recurring charge \$19.99 collected from cool-threads',
    metadata: {'amount': '1999'},
  ),
  AppEvent(
    id: 'evt-18', date: _now.subtract(const Duration(days: 8)),
    type: EventType.billingSuccess, appId: 'app-1',
    storeDomain: 'daily-deals.myshopify.com',
    title: 'Billing succeeded',
    description: 'Recurring charge \$19.99 collected from daily-deals',
    metadata: {'amount': '1999'},
  ),
  AppEvent(
    id: 'evt-19', date: _now.subtract(const Duration(days: 11)),
    type: EventType.billingSuccess, appId: 'app-3',
    storeDomain: 'glow-beauty.myshopify.com',
    title: 'Billing succeeded',
    description: 'Recurring charge \$49.99 collected from glow-beauty',
    metadata: {'amount': '4999'},
  ),
  AppEvent(
    id: 'evt-20', date: _now.subtract(const Duration(days: 14)),
    type: EventType.billingSuccess, appId: 'app-1',
    storeDomain: 'acme-store.myshopify.com',
    title: 'Billing succeeded',
    description: 'Recurring charge \$49.99 collected from acme-store',
    metadata: {'amount': '4999'},
  ),
  AppEvent(
    id: 'evt-21', date: _now.subtract(const Duration(days: 20)),
    type: EventType.billingSuccess, appId: 'app-2',
    storeDomain: 'glow-beauty.myshopify.com',
    title: 'Billing succeeded',
    description: 'Recurring charge \$19.99 collected from glow-beauty',
    metadata: {'amount': '1999'},
  ),
  AppEvent(
    id: 'evt-22', date: _now.subtract(const Duration(days: 25)),
    type: EventType.billingSuccess, appId: 'app-1',
    storeDomain: 'eco-shop.myshopify.com',
    title: 'Billing succeeded',
    description: 'Recurring charge \$99.99 collected from eco-shop',
    metadata: {'amount': '9999'},
  ),

  // --- Usage Charges (6) ---
  AppEvent(
    id: 'evt-23', date: _now.subtract(const Duration(days: 1, hours: 10)),
    type: EventType.usageCharge, appId: 'app-1',
    storeDomain: 'eco-shop.myshopify.com',
    title: 'Usage charge recorded',
    description: 'Usage charge \$12.50 from eco-shop',
    metadata: {'amount': '1250'},
  ),
  AppEvent(
    id: 'evt-24', date: _now.subtract(const Duration(days: 3, hours: 4)),
    type: EventType.usageCharge, appId: 'app-1',
    storeDomain: 'acme-store.myshopify.com',
    title: 'Usage charge recorded',
    description: 'Usage charge \$8.75 from acme-store',
    metadata: {'amount': '875'},
  ),
  AppEvent(
    id: 'evt-25', date: _now.subtract(const Duration(days: 6, hours: 7)),
    type: EventType.usageCharge, appId: 'app-3',
    storeDomain: 'bright-gadgets.myshopify.com',
    title: 'Usage charge recorded',
    description: 'Usage charge \$15.00 from bright-gadgets',
    metadata: {'amount': '1500'},
  ),
  AppEvent(
    id: 'evt-26', date: _now.subtract(const Duration(days: 10)),
    type: EventType.usageCharge, appId: 'app-1',
    storeDomain: 'fresh-foods.myshopify.com',
    title: 'Usage charge recorded',
    description: 'Usage charge \$5.25 from fresh-foods',
    metadata: {'amount': '525'},
  ),
  AppEvent(
    id: 'evt-27', date: _now.subtract(const Duration(days: 16)),
    type: EventType.usageCharge, appId: 'app-3',
    storeDomain: 'glow-beauty.myshopify.com',
    title: 'Usage charge recorded',
    description: 'Usage charge \$9.80 from glow-beauty',
    metadata: {'amount': '980'},
  ),
  AppEvent(
    id: 'evt-28', date: _now.subtract(const Duration(days: 23)),
    type: EventType.usageCharge, appId: 'app-1',
    storeDomain: 'daily-deals.myshopify.com',
    title: 'Usage charge recorded',
    description: 'Usage charge \$11.00 from daily-deals',
    metadata: {'amount': '1100'},
  ),

  // --- Subscription Activated (5) ---
  AppEvent(
    id: 'evt-29', date: _now.subtract(const Duration(days: 0, hours: 5)),
    type: EventType.subscriptionActivated, appId: 'app-1',
    storeDomain: 'bright-gadgets.myshopify.com',
    title: 'Subscription activated',
    description: 'bright-gadgets activated Pro plan for InventorySync Pro',
    metadata: {'plan': 'Pro'},
  ),
  AppEvent(
    id: 'evt-30', date: _now.subtract(const Duration(days: 3, hours: 2)),
    type: EventType.subscriptionActivated, appId: 'app-2',
    storeDomain: 'fresh-foods.myshopify.com',
    title: 'Subscription activated',
    description: 'fresh-foods activated Starter plan for ReviewBoost',
    metadata: {'plan': 'Starter'},
  ),
  AppEvent(
    id: 'evt-31', date: _now.subtract(const Duration(days: 7, hours: 6)),
    type: EventType.subscriptionActivated, appId: 'app-3',
    storeDomain: 'acme-store.myshopify.com',
    title: 'Subscription activated',
    description: 'acme-store activated Basic plan for ShipTracker',
    metadata: {'plan': 'Basic'},
  ),
  AppEvent(
    id: 'evt-32', date: _now.subtract(const Duration(days: 15, hours: 3)),
    type: EventType.subscriptionActivated, appId: 'app-1',
    storeDomain: 'dusk-decor.myshopify.com',
    title: 'Subscription activated',
    description: 'dusk-decor activated Starter plan for InventorySync Pro',
    metadata: {'plan': 'Starter'},
  ),
  AppEvent(
    id: 'evt-33', date: _now.subtract(const Duration(days: 22, hours: 1)),
    type: EventType.subscriptionActivated, appId: 'app-2',
    storeDomain: 'ink-press.myshopify.com',
    title: 'Subscription activated',
    description: 'ink-press activated Pro plan for ReviewBoost',
    metadata: {'plan': 'Pro'},
  ),

  // --- Plan Upgrades (3) ---
  AppEvent(
    id: 'evt-34', date: _now.subtract(const Duration(days: 2, hours: 4)),
    type: EventType.planUpgrade, appId: 'app-1',
    storeDomain: 'eco-shop.myshopify.com',
    title: 'Plan upgraded',
    description: 'eco-shop upgraded from Pro to Enterprise on InventorySync Pro',
    metadata: {'from': 'Pro', 'to': 'Enterprise'},
  ),
  AppEvent(
    id: 'evt-35', date: _now.subtract(const Duration(days: 8, hours: 2)),
    type: EventType.planUpgrade, appId: 'app-2',
    storeDomain: 'acme-store.myshopify.com',
    title: 'Plan upgraded',
    description: 'acme-store upgraded from Starter to Pro on ReviewBoost',
    metadata: {'from': 'Starter', 'to': 'Pro'},
  ),
  AppEvent(
    id: 'evt-36', date: _now.subtract(const Duration(days: 19)),
    type: EventType.planUpgrade, appId: 'app-3',
    storeDomain: 'glow-beauty.myshopify.com',
    title: 'Plan upgraded',
    description: 'glow-beauty upgraded from Basic to Pro on ShipTracker',
    metadata: {'from': 'Basic', 'to': 'Pro'},
  ),

  // --- Reviews Submitted (3) ---
  AppEvent(
    id: 'evt-37', date: _now.subtract(const Duration(days: 1, hours: 8)),
    type: EventType.reviewSubmitted, appId: 'app-1',
    storeDomain: 'acme-store.myshopify.com',
    title: 'Review submitted',
    description: 'acme-store left a 5-star review for InventorySync Pro',
    metadata: {'rating': '5'},
  ),
  AppEvent(
    id: 'evt-38', date: _now.subtract(const Duration(days: 5, hours: 3)),
    type: EventType.reviewSubmitted, appId: 'app-2',
    storeDomain: 'eco-shop.myshopify.com',
    title: 'Review submitted',
    description: 'eco-shop left a 4-star review for ReviewBoost',
    metadata: {'rating': '4'},
  ),
  AppEvent(
    id: 'evt-39', date: _now.subtract(const Duration(days: 17)),
    type: EventType.reviewSubmitted, appId: 'app-3',
    storeDomain: 'fresh-foods.myshopify.com',
    title: 'Review submitted',
    description: 'fresh-foods left a 5-star review for ShipTracker',
    metadata: {'rating': '5'},
  ),

  // --- Billing Failures (3) ---
  AppEvent(
    id: 'evt-40', date: _now.subtract(const Duration(days: 1, hours: 1)),
    type: EventType.billingFailure, appId: 'app-1',
    storeDomain: 'alpha-outlet.myshopify.com',
    title: 'Billing failed',
    description: 'Recurring charge \$19.99 failed for alpha-outlet (card declined)',
    metadata: {'reason': 'card_declined'},
  ),
  AppEvent(
    id: 'evt-41', date: _now.subtract(const Duration(days: 4, hours: 6)),
    type: EventType.billingFailure, appId: 'app-2',
    storeDomain: 'beta-mart.myshopify.com',
    title: 'Billing failed',
    description: 'Recurring charge \$19.99 failed for beta-mart (insufficient funds)',
    metadata: {'reason': 'insufficient_funds'},
  ),
  AppEvent(
    id: 'evt-42', date: _now.subtract(const Duration(days: 6, hours: 9)),
    type: EventType.billingFailure, appId: 'app-1',
    storeDomain: 'craft-corner.myshopify.com',
    title: 'Billing failed',
    description: 'Recurring charge \$49.99 failed for craft-corner (expired card)',
    metadata: {'reason': 'expired_card'},
  ),

  // --- Risk State Changes (3) ---
  AppEvent(
    id: 'evt-43', date: _now.subtract(const Duration(days: 3, hours: 7)),
    type: EventType.riskStateChange, appId: 'app-1',
    storeDomain: 'alpha-outlet.myshopify.com',
    title: 'Risk state changed',
    description: 'alpha-outlet risk changed: Safe to 1 Cycle Missed',
    metadata: {'from': 'safe', 'to': 'oneCycleMissed'},
  ),
  AppEvent(
    id: 'evt-44', date: _now.subtract(const Duration(days: 10, hours: 3)),
    type: EventType.riskStateChange, appId: 'app-1',
    storeDomain: 'ink-press.myshopify.com',
    title: 'Risk state changed',
    description: 'ink-press risk changed: 1 Cycle Missed to 2 Cycles Missed',
    metadata: {'from': 'oneCycleMissed', 'to': 'twoCycleMissed'},
  ),
  AppEvent(
    id: 'evt-45', date: _now.subtract(const Duration(days: 21)),
    type: EventType.riskStateChange, appId: 'app-2',
    storeDomain: 'neon-arcade.myshopify.com',
    title: 'Risk state changed',
    description: 'neon-arcade risk changed: 2 Cycles Missed to Churned',
    metadata: {'from': 'twoCycleMissed', 'to': 'churned'},
  ),

  // --- Plan Downgrades (2) ---
  AppEvent(
    id: 'evt-46', date: _now.subtract(const Duration(days: 5, hours: 1)),
    type: EventType.planDowngrade, appId: 'app-1',
    storeDomain: 'beta-mart.myshopify.com',
    title: 'Plan downgraded',
    description: 'beta-mart downgraded from Pro to Starter on InventorySync Pro',
    metadata: {'from': 'Pro', 'to': 'Starter'},
  ),
  AppEvent(
    id: 'evt-47', date: _now.subtract(const Duration(days: 13)),
    type: EventType.planDowngrade, appId: 'app-2',
    storeDomain: 'craft-corner.myshopify.com',
    title: 'Plan downgraded',
    description: 'craft-corner downgraded from Pro to Basic on ReviewBoost',
    metadata: {'from': 'Pro', 'to': 'Basic'},
  ),

  // --- Subscription Cancelled (2) ---
  AppEvent(
    id: 'evt-48', date: _now.subtract(const Duration(days: 4, hours: 3)),
    type: EventType.subscriptionCancelled, appId: 'app-1',
    storeDomain: 'maple-candles.myshopify.com',
    title: 'Subscription cancelled',
    description: 'maple-candles cancelled InventorySync Pro subscription',
  ),
  AppEvent(
    id: 'evt-49', date: _now.subtract(const Duration(days: 14, hours: 5)),
    type: EventType.subscriptionCancelled, appId: 'app-2',
    storeDomain: 'neon-arcade.myshopify.com',
    title: 'Subscription cancelled',
    description: 'neon-arcade cancelled ReviewBoost subscription',
  ),

  // --- Uninstall (1) ---
  AppEvent(
    id: 'evt-50', date: _now.subtract(const Duration(days: 6, hours: 2)),
    type: EventType.appUninstall, appId: 'app-1',
    storeDomain: 'maple-candles.myshopify.com',
    title: 'App uninstalled',
    description: 'maple-candles uninstalled InventorySync Pro',
  ),
]..sort((a, b) => b.date.compareTo(a.date));
